apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-probes-mapped
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-probes-mapped
  template:
    metadata:
      labels:
        app: nginx-probes-mapped
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          livenessProbe:
            initialDelaySeconds: 1
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
            httpGet:
              path: /
              httpHeaders:
                - name: Host
                  value: myapplication1.com
              port: 80
