# permissions for end users to edit loadtests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loadtest-editor-role
rules:
- apiGroups:
  - loadtest.artillery.io
  resources:
  - loadtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loadtest.artillery.io
  resources:
  - loadtests/status
  verbs:
  - get
