apiVersion: loadtest.artillery.io/v1alpha1
kind: LoadTest
metadata:
  name: loadtest-other
  namespace: default
spec:
  # Add fields here
  count: 5
  environment: dev
  testScript:
    config:
      configMap: load-test-other-config
    external:
      payload:
        configMaps:
          - csv-payload-other-1
          - csv-payload-other-2
          - csv-payload-other-3
      processor:
        main:
          configMap: my-functions-js
        related:
          configMaps:
            - package-json-other
