apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-no-probes-mapped
  name: nginx-no-probes-mapped
  namespace: default
spec:
  ports:
    - name: nginx-http-port
      port: 80
  selector:
    app: nginx-no-probes-mapped
  sessionAffinity: None
  type: ClusterIP
