name: publish-release-operator
on:
  create:

jobs:
  publish-release-operator-image:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        if: success() && startsWith(github.ref, 'refs/tags/')

      - name: Set tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and push versioned image
        env:
          VERSION: ${{ steps.vars.outputs.tag }}
          IMAGE_REPO_OWNER: ghcr.io/artilleryio
        run: |
          echo $VERSION
          echo $IMAGE_REPO_OWNER
          make docker-build docker-push

      - name: Tag and push latest image
        env:
          VERSION: latest
          IMAGE_REPO_OWNER: ghcr.io/artilleryio
        run: |
          echo $VERSION
          echo $IMAGE_REPO_OWNER
          make docker-tag docker-push

      - name: Create a release draft for the operator image based on version tag
        id: create-release-draft
        uses: ecampidoglio/auto-release-draft@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print the URL of the release draft
        if: steps.create-release-draft.outputs.release-url != ''
        run: echo ${{ steps.create-release-draft.outputs.release-url }}
