name: release-operator
on:
  create:
    tags:
      - v**-artillery-operator-alpha
jobs:
  publish-image-and-draft-release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set release version as output
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF_NAME/-artillery-operator-alpha/}

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and push versioned image
        env:
          VERSION: ${{ steps.vars.outputs.version }}
          IMAGE_REPO_OWNER: ghcr.io/artilleryio
        run: |
          echo $VERSION
          echo $IMAGE_REPO_OWNER
          make docker-build docker-push

      - name: Tag and push latest image
        env:
          VERSION: latest
          IMAGE_REPO_OWNER: ghcr.io/artilleryio
        run: |
          echo $VERSION
          echo $IMAGE_REPO_OWNER
          make docker-tag docker-push

      - name: Auto Release Draft
        # You may pin to the exact commit or the version.
        # uses: ecampidoglio/auto-release-draft@c1617ba27945d4c224bbe1552e924cf539b508e9
        uses: ecampidoglio/auto-release-draft@v1.0.0
        with:
          # The GITHUB_TOKEN used to authenticate to the current repository
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print the URL of the release draft
        if: steps.create-release-draft.outputs.release-url != ''
        run: echo ${{ steps.create-release-draft.outputs.release-url }}
