name: tag-and-publish-operator
on:
  push:
    tags:
      - v**
jobs:
  tag-and-publish-operator-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build and push versioned image
        env:
          VERSION: ${{ env.GITHUB_REF_NAME }}
          IMAGE_REPO_OWNER: ghcr.io/artilleryio
        run: |
          echo $VERSION
          echo $IMAGE_REPO_OWNER
          make docker-build docker-push

      - name: Tag and push latest image
        env:
          VERSION: latest
          IMAGE_REPO_OWNER: ghcr.io/artilleryio
        run: |
          echo $VERSION
          echo $IMAGE_REPO_OWNER
          make docker-tag docker-push
